// <auto-generated />
using System;
using AnimeCollection.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimeCollection.API.Migrations
{
    [DbContext(typeof(AnimeCollectionContext))]
    partial class AnimeCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnimeCollection.DAL.Entities.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfPremiere")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NumberOfSeries")
                        .HasColumnType("int");

                    b.Property<string>("OriginalDirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimeCollection");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a53a23a-f4fc-4674-b43c-1e91d97b763e"),
                            AuthorId = new Guid("7aba6f15-1c72-4895-a790-378910dd9f6b"),
                            DateOfPremiere = new DateTime(1995, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorName = "Yoshifumi Kondo",
                            NumberOfSeries = 0,
                            OriginalTitle = "耳をすませば",
                            StudioId = new Guid("32ddd588-272f-4e61-ad82-a6799063e44e"),
                            Title = "Whisper of the Heart"
                        },
                        new
                        {
                            Id = new Guid("00c535c2-6abc-4480-a64b-00f6cc49cc5d"),
                            AuthorId = new Guid("eac6b73d-4fdc-4130-85ff-7ae7c10f1e61"),
                            DateOfPremiere = new DateTime(1999, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorName = "Konosuke Uda",
                            NumberOfSeries = 990,
                            OriginalTitle = "ワンピース",
                            StudioId = new Guid("aa134a5c-a0c4-4d7f-bfb0-c4994c2d578a"),
                            Title = "One Piece"
                        },
                        new
                        {
                            Id = new Guid("53d382c0-8522-4bee-96ab-6b4e1cadb1e1"),
                            AuthorId = new Guid("00c84da1-a331-48a2-aa1d-f96e937abda3"),
                            DateOfPremiere = new DateTime(2004, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DirectorName = "Abe Noriyuki",
                            NumberOfSeries = 366,
                            OriginalTitle = "ブリーチ",
                            StudioId = new Guid("a7cdeec1-e15b-4d33-a83c-c05c79bfad76"),
                            Title = "Bleach"
                        });
                });

            modelBuilder.Entity("AnimeCollection.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OriginalAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00c84da1-a331-48a2-aa1d-f96e937abda3"),
                            Alias = "Tite Kubo",
                            DateOfBirth = new DateTime(1977, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Noriyaki Kubo",
                            OriginalName = "久保 宣章"
                        },
                        new
                        {
                            Id = new Guid("eac6b73d-4fdc-4130-85ff-7ae7c10f1e61"),
                            DateOfBirth = new DateTime(1975, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oda Eiichiro",
                            OriginalName = "尾田 栄一郎"
                        },
                        new
                        {
                            Id = new Guid("92437869-7e2a-4523-a991-69870ceff328"),
                            DateOfBirth = new DateTime(1941, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hayao Miyazaki",
                            OriginalName = "宮崎 駿"
                        },
                        new
                        {
                            Id = new Guid("7aba6f15-1c72-4895-a790-378910dd9f6b"),
                            DateOfBirth = new DateTime(1962, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hiiragi Aoi",
                            OriginalName = "柊 あおい"
                        });
                });

            modelBuilder.Entity("AnimeCollection.DAL.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalPresidentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresidentName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("YearOfFoundation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7cdeec1-e15b-4d33-a83c-c05c79bfad76"),
                            Name = "Studio Pierrot",
                            OriginalName = "株式会社ぴえろ",
                            PresidentName = "Yuji Nunokawa",
                            YearOfFoundation = 1979
                        },
                        new
                        {
                            Id = new Guid("aa134a5c-a0c4-4d7f-bfb0-c4994c2d578a"),
                            Name = "Toei Animation",
                            OriginalName = "東映アニメーション株式会社",
                            YearOfFoundation = 1956
                        },
                        new
                        {
                            Id = new Guid("32ddd588-272f-4e61-ad82-a6799063e44e"),
                            Name = "Studio Ghibli",
                            OriginalName = "スタジオジブリ",
                            PresidentName = "Hayao Miyazaki",
                            YearOfFoundation = 1985
                        });
                });

            modelBuilder.Entity("AnimeCollection.DAL.Entities.Anime", b =>
                {
                    b.HasOne("AnimeCollection.DAL.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeCollection.DAL.Entities.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Studio");
                });
#pragma warning restore 612, 618
        }
    }
}
